{% set name = "atpublic" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4f260104679e235db2665e8d4ef4b9ea79785fe540926659c775e79dec296d9


build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - pdm-pep517
  run:
    - python >=3.6

test:
  imports:
    - public
    - public.public
    - public.private
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://public.readthedocs.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: |
    A very simple decorator and function which populates a module’s __all__ and optionally 
    the module globals.
  doc_url: https://public.readthedocs.io

extra:
  recipe-maintainers:
    - johanneskoester
