{% set name = "atpublic" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f40433219e124edf115c6c363808ca6f0e1cfa7d160d86b2fb94793086d1294


build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - pdm-backend
  run:
    - python >=3.8

test:
  imports:
    - public
    - public.public
    - public.private
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://public.readthedocs.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: |
    A very simple decorator and function which populates a module’s __all__ and optionally 
    the module globals.
  doc_url: https://public.readthedocs.io

extra:
  recipe-maintainers:
    - keller00
    - johanneskoester
