{% set name = "atpublic" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82a2f2c0343ac67913f67cdee8fa4da294a4d6b863111527a459c8e4d1a646c8

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.0
  run:
    - python >=3.0

test:
  imports:
    - public
    - public.tests

about:
  home: http://public.readthedocs.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: |
    A very simple decorator and function which populates a module’s __all__ and optionally 
    the module globals. This provides both a pure-Python implementation and an optional C 
    implementation.
  doc_url: https://public.readthedocs.io

extra:
  recipe-maintainers:
    - johanneskoester
